# Generated by Django 5.0.2 on 2024-03-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_contributor_project_contributor_user"),
        ("projects", "0002_alter_project_description_alter_project_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contributor",
            options={"ordering": ["-date_joined"]},
        ),
        migrations.AlterUniqueTogether(
            name="contributor",
            unique_together={("user", "project")},
        ),
    ]
