# Generated by Django 5.0.2 on 2024-03-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_contributor_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="softuser",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
