# Generated by Django 5.0.2 on 2024-03-21 16:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_issue_priority_alter_issue_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
